### ISSUE TITLE
Please create an lp5.1 or cm-12.1 branch, I want to start maintaining this for the D800! (LG G2) and other variants. 

### ISSUE THREAD

**Issue by ghost** [DirtyUnicorns/android_device_lge_d800#1]
https://github.com/TeamBliss-Devices/android_kernel_lge_msm8974

I would make the pull request but I don't know how to accross seperate branches (kitkat and lp5.1) -- thank you.

Rest of device repos:

https://github.com/TeamBliss-Devices/android_device_lge_g2-common
https://github.com/TeamBliss-Devices/android_device_lge_d802
https://github.com/TeamBliss-Devices/android_device_lge_d800
https://github.com/TeamBliss-Devices/proprietary_vendor_lge

all are at lp5.1

Also, I HIGHLY RECCOMEND USING THIS KENREL ENTIRELY instead of the TB-D repo one! 
https://github.com/RenderBroken/msm8974_G2_render_kernel
branch: cm-12.0

I just built BlissPop with this roomservice, please create compatible Dirty Unicorns repos so I can build this awesome ROM as well! 
https://github.com/berryman13/local_manifests/blob/bliss-5.1/bliss-5.1_roomservice.xml

**Comment by nychitman1** [comment]
No. That's not how we do things.

**Comment by ghost** [comment]
Okay. I'm having a hard time finding any centralized area describing how to apply to become a maintainer. 
http://www.pac-rom.com/#BecomeAMaintainer

This really helped me get started with this ROM, but I don't know how Dirty Unicorns does it, github or gerrit? Can I get a little bit of an inclination of how to submit my own pull requests? The google+ page is plastered with people saying this, that, and the other. 

I'm a totally qualified maintainer/developer here man, willing to get this ROM running on a device which it currently doesn't yet. What's wrong with that?

**Comment by BoredOutOfMyGit** [comment]
We're not expanding to other devices. 

If you want to do unofficial builds, then I can't stop you there as long as you're maintaining credits/thanks and obeying the GPL

tl'dr.......you can't become a maintainer

**Comment by chasmodo** [comment]
Also, we don't need maintainers who don't know that commits are submitted to Gerrit, not via pull requests. 

Not really.
